user:
    resource: "@UserBundle/Controller/"
    type:     annotation
    prefix:   /

pai_postman:
    type:     rest
    prefix:   /api
    resource: "@PostmanBundle/Resources/config/routing.yml"
app:
    resource: "@AppBundle/Controller/"
    type:     annotation
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"